### PR TITLE
Be theoritically compatible with guzzle 7

### PR DESCRIPTION
**Pull request by drzraf**

### CODE REVIEW

**Comment by drzraf** [comment]
ping?

**Review by jasonraimondi — APPROVED** [review]

**Comment by drzraf** [comment]
reping :) ?

**Comment by jasonraimondi** [comment]
I am not allowed to merge anything anymore, but fwiw it really seems like this is harmless @toddcornett @kevinthrailkill. If you dont hear back from them, I would assume they are just focused on other things, and at that point you should consider just forking the repository and working off the fork.

**Comment by drzraf** [comment]
@toddcornett / @kevinthrailkill

**Comment by timohuisman** [comment]
@toddcornett, any chance that you could tag a new release which contains this commit? Would be really helpful!

**Comment by toddcornett** [comment]
@timohuisman - Apologies for the delay.  Just pushed a new release out with this change!

**Pull request merged**
